# docker-compose.yml

x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2023-10-16T04-13-43Z
  command: server --console-address ":9001" http://minio{1...2}/data{1...2}
  expose:
    - '9000'
    - '9001'
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
    interval: 30s
    timeout: 20s
    retries: 3

version: '3.8'
services:
  postgres-writer:
    image: bitnami/postgresql:16
    restart: always
    environment:
      - POSTGRESQL_USERNAME=universal-api
      - POSTGRESQL_PASSWORD=universal-api
      - POSTGRESQL_DATABASE=universal-api
      - POSTGRESQL_POSTGRES_PASSWORD=root
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./infra/postgresql/writer-data:/bitnami/postgresql
    ports:
      - '6432:5432'
  postgres-reader:
    image: bitnami/postgresql:16
    restart: always
    depends_on:
      - postgres-writer
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=postgres-writer
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - '6433:5432'

  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  tracing:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '9000:9000'
      - '9001:9001'
    depends_on:
      - minio1
      - minio2

  meilisearch:
    image: getmeili/meilisearch
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    ports:
      - ${MEILI_PORT:-7700}:7700
    volumes:
      - ./infra/search/meilisearch/data.ms:/data.ms
    restart: unless-stopped

volumes:
  cache:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
