export enum InventoryEvents {
  INVENTORY_WILDCARD = 'inventory.*',
  BRAND_WILDCARD = 'inventory.brand.*',
  BRAND_CREATED = 'inventory.brand.created',
  BRAND_UPDATED = 'inventory.brand.updated',
  BRAND_DELETED = 'inventory.brand.deleted',
  SUPPLIER_WILDCARD = 'inventory.supplier.*',
  SUPPLIER_CREATED = 'inventory.supplier.created',
  SUPPLIER_UPDATED = 'inventory.supplier.updated',
  SUPPLIER_DELETED = 'inventory.supplier.deleted',
  WAREHOUSE_WILDCARD = 'inventory.warehouse.*',
  WAREHOUSE_CREATED = 'inventory.warehouse.created',
  WAREHOUSE_UPDATED = 'inventory.warehouse.updated',
  WAREHOUSE_DELETED = 'inventory.warehouse.deleted',
  PRODUCT_WILDCARD = 'inventory.product.*',
  PRODUCT_CREATED = 'inventory.product.created',
  PRODUCT_UPDATED = 'inventory.product.updated',
  PRODUCT_DELETED = 'inventory.product.deleted',
  STOCK_WILDCARD = 'inventory.stock.*',
  STOCK_CREATED = 'inventory.stock.created',
  STOCK_UPDATED = 'inventory.stock.updated',
  STOCK_DELETED = 'inventory.stock.deleted',
  STOCK_LEDGER_WILDCARD = 'inventory.stock-ledger.*',
  STOCK_LEDGER_CREATED = 'inventory.stock-ledger.created',
  STOCK_LEDGER_UPDATED = 'inventory.stock-ledger.updated',
  STOCK_LEDGER_DELETED = 'inventory.stock-ledger.deleted',
}
