export enum OrganizationEvents {
  ORGANIZATION_WILDCARD = 'organization.*',
  GROUP_WILDCARD = 'organization.group.*',
  GROUP_CREATED = 'organization.group.created',
  GROUP_UPDATED = 'organization.group.updated',
  GROUP_DELETED = 'organization.group.deleted',
  GROUP_ASSOCIATION_WILDCARD = 'organization.group-association.*',
  GROUP_ASSOCIATION_CREATED = 'organization.group-association.created',
  GROUP_ASSOCIATION_UPDATED = 'organization.group-association.updated',
  GROUP_ASSOCIATION_DELETED = 'organization.group-association.deleted',
  MERCHANT_WILDCARD = 'organization.merchant.*',
  MERCHANT_CREATED = 'organization.merchant.created',
  MERCHANT_UPDATED = 'organization.merchant.updated',
  MERCHANT_DELETED = 'organization.merchant.deleted',
  MERCHANT_ASSOCIATION_WILDCARD = 'organization.merchant-association.*',
  MERCHANT_ASSOCIATION_CREATED = 'organization.merchant-association.created',
  MERCHANT_ASSOCIATION_UPDATED = 'organization.merchant-association.updated',
  MERCHANT_ASSOCIATION_DELETED = 'organization.merchant-association.deleted',
  FACILITY_WILDCARD = 'organization.facility.*',
  FACILITY_CREATED = 'organization.facility.created',
  FACILITY_UPDATED = 'organization.facility.updated',
  FACILITY_DELETED = 'organization.facility.deleted',
  PERSON_WILDCARD = 'organization.person.*',
  PERSON_CREATED = 'organization.person.created',
  PERSON_UPDATED = 'organization.person.updated',
  PERSON_DELETED = 'organization.person.deleted',
}
