export enum DocumentEvents {
  DOCUMENT_WILDCARD = 'document.*',
  DOCUMENT_CREATED = 'document.created',
  DOCUMENT_UPDATED = 'document.updated',
  DOCUMENT_DELETED = 'document.deleted',
  DOCUMENT_FIELD_DATA_WILDCARD = 'document.document-field-data.*',
  DOCUMENT_FIELD_DATA_CREATED = 'document.document-field-data.created',
  DOCUMENT_FIELD_DATA_UPDATED = 'document.document-field-data.updated',
  DOCUMENT_FIELD_DATA_DELETED = 'document.document-field-data.deleted',
  DOCUMENT_TEMPLATE_WILDCARD = 'document.document-template.*',
  DOCUMENT_TEMPLATE_CREATED = 'document.document-template.created',
  DOCUMENT_TEMPLATE_UPDATED = 'document.document-template.updated',
  DOCUMENT_TEMPLATE_DELETED = 'document.document-template.deleted',
  DOCUMENT_TEMPLATE_FIELD_WILDCARD = 'document.document-template-field.*',
  DOCUMENT_TEMPLATE_FIELD_CREATED = 'document.document-template-field.created',
  DOCUMENT_TEMPLATE_FIELD_UPDATED = 'document.document-template-field.updated',
  DOCUMENT_TEMPLATE_FIELD_DELETED = 'document.document-template-field.deleted',
  DOCUMENT_TEMPLATE_FIELD_OPTION_WILDCARD = 'document.document-template-field-option.*',
  DOCUMENT_TEMPLATE_FIELD_OPTION_CREATED = 'document.document-template-field-option.created',
  DOCUMENT_TEMPLATE_FIELD_OPTION_UPDATED = 'document.document-template-field-option.updated',
  DOCUMENT_TEMPLATE_FIELD_OPTION_DELETED = 'document.document-template-field-option.deleted',
}
